"feature_cost": Null
"lr": 0.01
"lambda_": 0.01
"delta_max": 0.01
"norm": 1
"t_max_min": 0.5
"loss_type": "BCE"
"y_target": [0, 1]
"binary_cat_features": False
"loss_threshold": 1e-3
"discretize": False
"sample": True
"lime_seed": 0
"seed": 0