feature_cost: "_optional_"
lr: 0.001
lambda_: 0.01
n_iter: 1000
t_max_min: 0.5
norm: 1
clamp: True
loss_type: "MSE"
y_target: [0, 1]
binary_cat_features: True
noise_variance: 0.01
invalidation_target: 0.45
inval_target_eps: 0.005